import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/component/Nav';

//Header, Nav

export const metadata: Metadata = {
  title: 'Seoul-Play',
  description: 'Seoul-Play Project Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="">
      <body className="bg-[#f5f5f5] w-full max-w-7xl mx-auto h-full">
        <header className="w-full h-[3vh]">
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
