import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/component/nav/Nav';

export const metadata: Metadata = {
  title: 'Seoul-Play',
  description: 'Seoul-Play Project Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-[#f5f5f5] text-gray-800 w-full max-w-7xl mx-auto min-h-screen flex flex-col">
        <header className="w-full bg-gradient-to-r from-red-500 to-red-600 text-white py-5 rounded-b-[30px] shadow-md px-6">
          <Nav />
        </header>
        <main className="flex-1 px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
