import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/component/Nav';

//Header, Nav

export const metadata: Metadata = {
  title: 'Seoul-Play',
  description: 'Seoul-Play Project Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <header>
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
